# Generated by Django 2.2.16 on 2021-11-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='email address', max_length=254, unique=True),
        ),
    ]
